timeout: 5

interface_branding: Teenager OS
interface_branding_colour: 6
interface_resolution: 1280x720
interface_help_hidden: no

backdrop: 1a1b2e
wallpaper: boot():/boot/limine/wallpaper.jpeg
wallpaper_style: stretched

term_foreground: cdd6f4
term_background: c01e1e2e
term_foreground_bright: cdd6f4
term_background_bright: 1e1e2e

term_palette: 1e1e2e;f38ba8;a6e3a1;f9e2af;89b4fa;cba6f7;89dceb;a6adc8
term_palette_bright: 585b70;f38ba8;a6e3a1;f9e2af;89b4fa;cba6f7;89dceb;cdd6f4

term_margin: 12
term_margin_gradient: 8

/Teenager OS
    protocol: linux
    kernel_path: boot():/boot/vmlinuz
    cmdline: modules=loop,squashfs,sd-mod,usb-storage quiet console=ttyS0 console=tty0 modloop=/boot/modloop
    module_path: boot():/boot/initramfs
